name: nemo_bathymetry
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - cartopy
  - cmocean
  - dask
  - matplotlib
  - numpy
  - os
  - pandas
  - pytables
  - scipy
  - xarray


